In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [2]:
# We start by loading the data
data = pd.read_csv('1.01. Simple linear regression.csv')

# Let's explore the top 5 rows of the df
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [4]:
# There is a single independent variable: 'SAT'
x = data['SAT']

# and a single dependent variable: 'GPA'
y = data['GPA']

In [6]:
x.shape, y.shape

((84,), (84,))

In [7]:
# In order to feed x to sklearn, it should be a 2D array (a matrix)
# Therefore, we must reshape it 
# Note that this will not be needed when we've got more than 1 feature (as the inputs will be a 2D array by default)

# x_matrix = x.values.reshape(84,1)
x_matrix = x.values.reshape(-1,1)

# Check the shape just in case
x_matrix.shape

(84, 1)

In [8]:
reg = LinearRegression()

In [10]:
reg.fit(x_matrix,y)

#normalize = False - does not refer to standardization - normalization here means
#subtracting the mean and dividing by the L2 norm

# fit intercept = True allows sklearn to fit with an intercept - if you don't want one,
# set it to False

# n_jobs allows us to choose the number of CPUs to use (useful for larger jobs)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
# R- sq
reg.score(x_matrix,y)

0.40600391479679765

In [13]:
# Coefficients of feats
reg.coef_

array([0.00165569])

In [14]:
reg.intercept_

0.27504029966028076

In [20]:

reg.predict(np.array([[1740]]))

array([3.15593751])

In [21]:
new_data = pd.DataFrame(data=[1740,1760],columns=['SAT'])
new_data

SAT
0  1740
1  1760

In [22]:
reg.predict(new_data)

array([3.15593751, 3.18905127])